///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTestSourceControl.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MainTest recording.
    /// </summary>
    [TestModule("636d4bb1-f8b5-42ae-b6f2-457f22482371", ModuleType.Recording, 1)]
    public partial class MainTest : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::MyTestSourceControl.MyTestSourceControlRepository repository.
        /// </summary>
        public static global::MyTestSourceControl.MyTestSourceControlRepository repo = global::MyTestSourceControl.MyTestSourceControlRepository.Instance;

        static MainTest instance = new MainTest();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MainTest()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MainTest Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabIntroduction.EnterYourName' at 30;7.", repo.ApplicationUnderTest.RxTabIntroduction.EnterYourNameInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.RxTabIntroduction.EnterYourName.Click("30;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'nedeljko' with focus on 'ApplicationUnderTest.RxTabIntroduction.EnterYourName'.", repo.ApplicationUnderTest.RxTabIntroduction.EnterYourNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.RxTabIntroduction.EnterYourName.PressKeys("nedeljko");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabIntroduction.BtnSubmitUserName' at 38;15.", repo.ApplicationUnderTest.RxTabIntroduction.BtnSubmitUserNameInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.RxTabIntroduction.BtnSubmitUserName.Click("38;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabIntroduction.Reset' at 21;11.", repo.ApplicationUnderTest.RxTabIntroduction.ResetInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.RxTabIntroduction.Reset.Click("21;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabIntroduction.EnterYourName' at 45;18.", repo.ApplicationUnderTest.RxTabIntroduction.EnterYourNameInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.RxTabIntroduction.EnterYourName.Click("45;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ranorex' with focus on 'ApplicationUnderTest.RxTabIntroduction.EnterYourName'.", repo.ApplicationUnderTest.RxTabIntroduction.EnterYourNameInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.RxTabIntroduction.EnterYourName.PressKeys("ranorex");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabIntroduction.BtnSubmitUserName' at 44;14.", repo.ApplicationUnderTest.RxTabIntroduction.BtnSubmitUserNameInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.RxTabIntroduction.BtnSubmitUserName.Click("44;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabIntroduction.Reset' at 20;3.", repo.ApplicationUnderTest.RxTabIntroduction.ResetInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.RxTabIntroduction.Reset.Click("20;3");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
